import AppKit
import CryptoKit

@MainActor
final class ClipboardMonitor {
    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?

    var suppressUntilChangeCount: Int = -1

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let t = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() { timer?.invalidate(); timer = nil }

    private func poll() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        if current == suppressUntilChangeCount { return }
        guard let item = makeItem() else { return }
        ClipboardStore.shared.addCaptured(item)
    }

    private func makeItem() -> ClipItem? {
        let types = pasteboard.types ?? []

        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")) { return nil }
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) { return nil }
        if Settings.shared.ignoreConcealed,
           types.contains(NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")) { return nil }

        let front = NSWorkspace.shared.frontmostApplication
        let src: NSRunningApplication?
        if front == nil || front?.bundleIdentifier == Bundle.main.bundleIdentifier {
            src = AppController.shared.lastActiveApp
        } else {
            src = front
        }
        let bundleID = src?.bundleIdentifier
        let appName = src?.localizedName

        func decorate(_ item: inout ClipItem) {
            item.sourceBundleID = bundleID
            item.sourceAppName = appName
        }

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self],
                                             options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            var item = ClipItem(type: .file,
                                text: urls.map(\.lastPathComponent).joined(separator: ", "),
                                fileURLs: urls.map(\.absoluteString))
            decorate(&item)
            return item
        }

        if types.contains(.png) || types.contains(.tiff) {
            if let data = pngData() {
                let hash = Self.sha256Hex(data)
                guard let name = ClipboardStore.shared.storeImageData(data) else { return nil }
                var item = ClipItem(type: .image, imageFileName: name, imageHash: hash)
                decorate(&item)
                return item
            }
        }

        let rtf = pasteboard.data(forType: .rtf)
        if let string = pasteboard.string(forType: .string), !string.isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            let type: ClipType
            if rtf != nil {
                type = .richText
            } else if isLink(trimmed) {
                type = .link
            } else {
                type = .text
            }
            var item = ClipItem(type: type, text: string, rtfData: rtf)
            decorate(&item)
            return item
        }

        if hasColorType(types), let color = NSColor(from: pasteboard) {
            var item = ClipItem(type: .color, colorHex: color.usingColorSpace(.sRGB)?.hexString)
            decorate(&item)
            return item
        }

        return nil
    }

    private func hasColorType(_ types: [NSPasteboard.PasteboardType]) -> Bool {
        types.contains { $0.rawValue.localizedCaseInsensitiveContains("color") }
    }

    private static func sha256Hex(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }

    private func pngData() -> Data? {
        if let data = pasteboard.data(forType: .png) { return data }
        guard let tiff = pasteboard.data(forType: .tiff),
              let rep = NSBitmapImageRep(data: tiff) else { return nil }
        return rep.representation(using: .png, properties: [:])
    }

    private func isLink(_ s: String) -> Bool {
        guard !s.contains(" "), !s.contains("\n"),
              let url = URL(string: s),
              let scheme = url.scheme?.lowercased(),
              ["http", "https"].contains(scheme),
              url.host != nil else { return false }
        return true
    }
}

private extension NSColor {
    convenience init?(from pasteboard: NSPasteboard) {
        guard let objs = pasteboard.readObjects(forClasses: [NSColor.self], options: nil) as? [NSColor],
              let c = objs.first else { return nil }
        self.init(cgColor: c.cgColor)
    }
}
